name: Dev builds

on:
  push:
    branches:
      - main
      - 'dev-build/*'

defaults:
  run:
    shell: bash

env:
  GO_VERSION: "1.20.5"

jobs:

  build:
    name: Build
    uses: ./.github/workflows/workflow-build.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_os: linux_arm64
            runs-on: ubuntu-20.04
            with-emulation: true
            fips: true
    with:
      arch_os: ${{ matrix.arch_os }}
      runs-on: ${{ matrix.runs-on }}
      fips: ${{ matrix.fips == true }}
      save-cache: true
